"""initial_schema

Revision ID: 19233e341367
Revises: 
Create Date: 2026-09-25 00:49:51.717262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19233e341367'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from backend.app.db.session import Base
    import backend.app.models  # register all models
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing_tables = set(insp.get_table_names())

    # Create all core tables if starting against a completely empty database
    Base.metadata.create_all(bind=bind, checkfirst=True)
    existing_tables = set(sa.inspect(bind).get_table_names())

    if 'background_jobs' not in existing_tables:
        op.create_table('background_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.String(length=64), nullable=False),
        sa.Column('job_type', sa.Enum('BATCH_PREDICTION', 'MODEL_TRAINING', 'DATASET_GENERATION', 'DRIFT_CALCULATION', 'EXPORT_REPORT', name='jobtype'), nullable=False),
        sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('progress', sa.Float(), nullable=True),
        sa.Column('result_json', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('background_jobs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_background_jobs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_background_jobs_job_id'), ['job_id'], unique=True)
            batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_background_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_id'))

    op.drop_table('background_jobs')
    # ### end Alembic commands ###
