"""add_parameters_json_to_jobs

Revision ID: 788c1d92d208
Revises: 19233e341367
Create Date: 2026-09-25 01:05:21.428724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788c1d92d208'
down_revision: Union[str, Sequence[str], None] = '19233e341367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    insp = sa.inspect(bind)
    cols = [c['name'] for c in insp.get_columns('background_jobs')]
    if 'parameters_json' not in cols:
        with op.batch_alter_table('background_jobs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('parameters_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_column('parameters_json')

    # ### end Alembic commands ###
